version: '2'

services:
  client:
      build: ./client-app
      expose:
        - 3000
      ports:
        - "3000:3000"

  server:
      build: ./server-app
      expose:
        - 8080
        - 8081
      ports:
        - "9080:8080"
        - "9081:8081"
      networks:
        app_net:
          ipv4_address: 172.18.0.22

networks:
    app_net:
        ipam:
            config:
            -  subnet: "172.18.0.0/16"

