version: '2'

services:
  client:
      build: ./client-app
      expose:
        - 3000
      ports:
        - "3000:3000"

  server:
      build: ./server-app
      expose:
        - 8080
        - 8081
      ports:
        - "9080:8080"
        - "9081:8081"

